#!/bin/sh
# Unpack the $dest manual file so that paches to it can be applied
#
# The difference to Debian manual page patch can then be evaluated.
# See diff.sh

dest=original

mkdir -p $dest
gzip -t  ../../doc/*1.gz &&
cp -f ../../doc/*1.gz $dest/ &&
gzip -fd $dest/*.gz

# End of file
